{{- if and .Values.persistence.enabled (ne .Values.mode "cluster") }}
apiVersion: v1  
kind: PersistentVolumeClaim  
metadata:  
  name: {{ include "cursus.fullname" . }}-logs  
spec:  
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
  accessModes:  
    - ReadWriteOnce
  resources:  
    requests:  
      storage: {{ .Values.persistence.logDir.size }}
{{- end }}
